"""Smoke tests: every module imports, and the two paths `run_endtoend` does not
exercise -- coefficient fitting and the panel plots -- actually run.

    uv run python testbed/test_smoke.py
"""

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import matplotlib                                                  # noqa: E402
matplotlib.use("Agg")

from campaigns import ot1, ot2                                     # noqa: E402
from otp.compare.calibrate import fit, turbine_flow_residual       # noqa: E402
from otp.compare.predict import compare_pump                       # noqa: E402
from otp.core.states import GasState, LiquidState, Propellant      # noqa: E402
from otp.experiments.records import ObservedPoint                  # noqa: E402
from otp.plotting.panels import Panel, sweep_plot, overlay_points   # noqa: E402
from otp.pump.analysis import Pump                                 # noqa: E402
from otp.pump.records import PumpChoices, PumpRequirements         # noqa: E402
from otp.pump.sizing import PumpSizingError, size_pump             # noqa: E402
from otp.turbine.analysis import Turbine                           # noqa: E402
from otp.turbine.records import TurbineCalibration                 # noqa: E402

PASS, FAIL = [], []


def check(name, fn):
    try:
        fn()
        PASS.append(name)
        print(f"  ok    {name}")
    except Exception as exc:
        FAIL.append((name, exc))
        print(f"  FAIL  {name}: {type(exc).__name__}: {exc}")


# ── the calibration path ────────────────────────────────────────────────────
def _synthetic_turbine_points(true_cd=0.88, n=6):
    """Points generated BY the model with a known nozzle_cd, so the fit has a
    right answer to recover.  This tests the fitting machinery, not the physics."""
    truth = TurbineCalibration(**{**vars(ot2.TURBINE_CALIBRATION), "nozzle_cd": true_cd})
    turbine = Turbine(ot2.TURBINE_GEOMETRY, truth)
    points = []
    for p0 in np.linspace(12.0, 28.0, n):
        gas = GasState(p0_bar=p0, T0_K=970.0, R=ot2.GG_R, gamma=ot2.GG_GAMMA,
                       source="synthetic")
        mdot = turbine.point_performance(rpm=20_000, gas=gas,
                                         p_exit_bar=1.01325).mdot
        points.append(ObservedPoint(
            run_id="synthetic", campaign="test", t0=0.0, t1=1.0, rpm=20_000.0,
            gas=gas, p_turbine_exit=1.01325,
            mdot_gg_ox=mdot * 0.6, mdot_gg_fuel=mdot * 0.4))
    return points, true_cd


def test_calibration_recovers_a_known_coefficient():
    points, true_cd = _synthetic_turbine_points()
    start = TurbineCalibration(**{**vars(ot2.TURBINE_CALIBRATION), "nozzle_cd": 1.0})
    result = fit(
        start, free={"nozzle_cd": (0.5, 1.05)}, points=points,
        residual_fn=turbine_flow_residual(
            lambda cal: Turbine(ot2.TURBINE_GEOMETRY, cal)))
    got = result.calibration.nozzle_cd
    assert abs(got - true_cd) < 1e-6, f"recovered {got}, wanted {true_cd}"
    assert result.rms_relative < 1e-9, f"residual {result.rms_relative}"
    assert "fitted to" in result.calibration.source, result.calibration.source
    print(f"        recovered nozzle_cd = {got:.6f} (true {true_cd}), "
          f"source stamped")


def test_calibration_refuses_underdetermined_fit():
    points, _ = _synthetic_turbine_points(n=2)
    start = ot2.TURBINE_CALIBRATION
    try:
        fit(start, free={"nozzle_cd": (0.5, 1.05), "k_sector": (0.0, 1.0),
                         "k_windage": (0.0, 1.0)},
            points=points,
            residual_fn=turbine_flow_residual(
                lambda cal: Turbine(ot2.TURBINE_GEOMETRY, cal)))
    except ValueError as exc:
        assert "underdetermined" in str(exc)
        return
    raise AssertionError("a 3-coefficient fit to 2 residuals should have been refused")


# ── the plotting path ───────────────────────────────────────────────────────
def _demo_pump():
    from pyfluids import FluidsList
    water = Propellant("N/A", FluidsList.Water, t_tank=293.15, p_tank=3.0)
    req = PumpRequirements(propellant=water, Q_req=3e-4, H_req=200.0)
    choices = PumpChoices(rpm=20_000, n_blades=6)
    pump = Pump(size_pump(req, choices, sizing_method="barske"), method="barske")
    inlet = LiquidState.from_propellant(water, p0_bar=3.0, T_K=293.15)
    return pump, req, inlet


def test_panels_render_with_measurement_overlay():
    pump, req, inlet = _demo_pump()
    panels = [
        Panel("Pressure rise (bar)", "Flow (L/s)",
              x=lambda p: p.Q * 1e3, y=lambda p: p.dp,
              obs_x=lambda o: o.Q * 1e3, obs_y=lambda o: o.dp_pump),
        Panel("Total head (m)", "Flow (L/s)",
              x=lambda p: p.Q * 1e3, y=lambda p: p.H_total_real,
              obs_x=lambda o: o.Q * 1e3, obs_y=lambda o: o.H_total),
    ]
    fig = sweep_plot(pump, panels, Qs=np.linspace(1e-5, 6e-4, 15),
                     sweep=("rpm", [10_000, 20_000, 30_000]),
                     fixed=dict(inlet=inlet), methods=["barske"], ncols=2)
    fake = [ObservedPoint(run_id="x", campaign="t", t0=0, t1=1, Q=2e-4,
                          dp_pump=12.0, H_total=120.0)]
    overlay_points(fig, panels, fake)
    out = HERE / "_smoke_panels.png"
    fig.savefig(out, dpi=60)
    assert out.exists() and out.stat().st_size > 5000
    out.unlink()


def test_size_pump_raises_instead_of_unbound_local():
    from pyfluids import FluidsList
    water = Propellant("N/A", FluidsList.Water, t_tank=293.15, p_tank=3.0)
    # 3000 m of head at 600 rpm is outside the bracket the Lock solve searches.
    # The notebook printed a message here and then raised UnboundLocalError from
    # an unrelated line; this must raise a named error that says what went wrong.
    req = PumpRequirements(propellant=water, Q_req=1e-3, H_req=3000.0)
    try:
        size_pump(req, PumpChoices(rpm=600, n_blades=6), sizing_method="lock")
    except PumpSizingError as exc:
        assert "H_req" in str(exc) and "rpm" in str(exc), str(exc)
        return
    raise AssertionError("expected PumpSizingError")


def test_pump_and_turbine_records_print():
    pump, req, inlet = _demo_pump()
    perf = pump.point_performance(Q=req.Q_req, rpm=20_000, inlet=inlet)
    for obj in (pump.geom, perf, ot2.TURBINE_GEOMETRY, ot2.TURBINE_CALIBRATION):
        text = str(obj)
        assert "\n" in text and type(obj).__name__ in text
        widest = max(len(line) for line in text.splitlines())
        assert widest < 200, f"{type(obj).__name__} prints {widest} chars wide"


def test_turbine_rejects_bad_boundaries():
    t = Turbine(ot2.TURBINE_GEOMETRY, ot2.TURBINE_CALIBRATION)
    for bad, why in ((30.0, "backpressure above inlet total"),):
        try:
            t.point_performance(rpm=20_000, gas=ot2.GG_DESIGN_GAS, p_exit_bar=bad)
        except ValueError:
            continue
        raise AssertionError(f"should have rejected {why}")


def main():
    print("smoke tests")
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            check(name[5:].replace("_", " "), fn)
    print(f"\n{len(PASS)} passed, {len(FAIL)} failed")
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
